
Setup


In [1]:
import os
import sys
import matplotlib.pyplot as plt


# Upgrade pip, just in case...
!{sys.executable} -m pip install --upgrade -q pip

     |████████████████████████████████| 2.1 MB 5.1 MB/s 


In [2]:
# Install requests for downloading data.
!{sys.executable} -m pip install --upgrade -q requests
!{sys.executable} -m pip install --upgrade -q pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 40.2 MB/s eta 0:00:00


In [3]:
#Import Dependencies

from builtins import range, input

from tensorflow.keras.layers import Input, Lambda, Dense, Flatten, AveragePooling2D, Dropout
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.metrics import confusion_matrix, roc_curve
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

import cv2
from glob import glob

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
from tensorflow.keras.utils import to_categorical

## COVID Dataset

TCIA Basics

In [4]:
import requests

tcia_utils_text = requests.get("https://github.com/kirbyju/TCIA_Notebooks/raw/main/tcia_utils.py")
with open('tcia_utils.py', 'wb') as f:
    f.write(tcia_utils_text.content)

In [5]:
import tcia_utils as tcia

In [6]:
# Download a "Shared Cart" that has been previously 
#    created via the NBIA webset 
#    (https://nbia.cancerimagingarchive.net)
# cartName = "nbia-77761668716072016" # Their example shared cart
# cartName = "nbia-47881669847357616" # Our lung cancer data's first subject
# cartName = "nbia-95651669947463238" # Cart with both cancer and covid data
cartName = "nbia-6761669942417940" # Cart with covid data

# retrieve cart metadata
cart_data = tcia.getSharedCart(cartName)

# download the series_uids list and return dataframe of metadata
df = tcia.downloadSeries(cart_data)

# display dataframe
display(df)

Calling...  https://services.cancerimagingarchive.net/nbia-api/services/v1/getContentsByName?name=nbia-6761669942417940
Downloading... https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage?NewFileNames=Yes&SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.99.1071.14850676509103506699400577275960
Downloading... https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage?NewFileNames=Yes&SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.99.1071.21083349907841416087078944245719
Downloading... https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage?NewFileNames=Yes&SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.99.1071.22090542070462647745743105373525
Downloading... https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage?NewFileNames=Yes&SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.99.1071.22366983673254100505145504004129
Downloading... https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage?NewFileNames=Yes&SeriesInstanceUID=1.3.6.1.4.

Series UID       Collection  \
0  1.3.6.1.4.1.14519.5.2.1.99.1071.14850676509103...  COVID-19-NY-SBU   
1  1.3.6.1.4.1.14519.5.2.1.99.1071.21083349907841...  COVID-19-NY-SBU   
2  1.3.6.1.4.1.14519.5.2.1.99.1071.22090542070462...  COVID-19-NY-SBU   
3  1.3.6.1.4.1.14519.5.2.1.99.1071.22366983673254...  COVID-19-NY-SBU   
4  1.3.6.1.4.1.14519.5.2.1.99.1071.30475546417294...  COVID-19-NY-SBU   
5  1.3.6.1.4.1.14519.5.2.1.99.1071.85179820664090...  COVID-19-NY-SBU   

  3rd Party Analysis                    Data Description URI Subject ID  \
0                 NO  https://doi.org/10.7937/TCIA.BBAG-2923    A034518   
1                 NO  https://doi.org/10.7937/TCIA.BBAG-2923    A034518   
2                 NO  https://doi.org/10.7937/TCIA.BBAG-2923    A034518   
3                 NO  https://doi.org/10.7937/TCIA.BBAG-2923    A034518   
4                 NO  https://doi.org/10.7937/TCIA.BBAG-2923    A034518   
5                 NO  https://doi.org/10.7937/TCIA.BBAG-2923    A034518   

                                           Study UID  \
0  1.3.6.1.4.1.14519.5.2.1.99.1071.28052166218470...   
1  1.3.6.1.4.1.14519.5.2.1.99.1071.28052166218470...   
2  1.3.6.1.4.1.14519.5.2.1.99.1071.28052166218470...   
3  1.3.6.1.4.1.14519.5.2.1.99.1071.28052166218470...   
4  1.3.6.1.4.1.14519.5.2.1.99.1071.28052166218470...   
5  1.3.6.1.4.1.14519.5.2.1.99.1071.28052166218470...   

                         Study Description  Study Date Series Description  \
0  CT ABD PELVISWITH CHEST IMAGES W IV CON  12-31-1900                2.0   
1  CT ABD PELVISWITH CHEST IMAGES W IV CON  12-31-1900      Body 3.000 CE   
2  CT ABD PELVISWITH CHEST IMAGES W IV CON  12-31-1900      Body 3.000 CE   
3  CT ABD PELVISWITH CHEST IMAGES W IV CON  12-31-1900        Lung 1.0 CE   
4  CT ABD PELVISWITH CHEST IMAGES W IV CON  12-31-1900        Body 5.0 CE   
5  CT ABD PELVISWITH CHEST IMAGES W IV CON  12-31-1900        Lung 5.0 CE   

  Manufacturer Modality              SOP Class UID Number of Images  \
0      TOSHIBA       CT  1.2.840.10008.5.1.4.1.1.2                2   
1      TOSHIBA       CT  1.2.840.10008.5.1.4.1.1.2              118   
2      TOSHIBA       CT  1.2.840.10008.5.1.4.1.1.2               89   
3      TOSHIBA       CT  1.2.840.10008.5.1.4.1.1.2              596   
4      TOSHIBA       CT  1.2.840.10008.5.1.4.1.1.2              120   
5      TOSHIBA       CT  1.2.840.10008.5.1.4.1.1.2              120   

   File Size Series Number                                       License Name  \
0    1314900      1.000000  Creative Commons Attribution 4.0 International...   
1  160721790      7.000000  Creative Commons Attribution 4.0 International...   
2  121222124      6.000000  Creative Commons Attribution 4.0 International...   
3  314916466      4.000000  Creative Commons Attribution 4.0 International...   
4   63405602      2.000000  Creative Commons Attribution 4.0 International...   
5   63405842      3.000000  Creative Commons Attribution 4.0 International...   

                                    License URL Annotation Size  
0  https://creativecommons.org/licenses/by/4.0/               0  
1  https://creativecommons.org/licenses/by/4.0/               0  
2  https://creativecommons.org/licenses/by/4.0/               0  
3  https://creativecommons.org/licenses/by/4.0/               0  
4  https://creativecommons.org/licenses/by/4.0/               0  
5  https://creativecommons.org/licenses/by/4.0/               0

In [7]:
# For this demo...

# Install itk for DICOM I/O and for reading DICOM into an itkImage 
#   that manages all DICOM field values, include acquistion details 
#   such as voxel image, image orientation, and image directions
#   which are critical to image processing and display
!{sys.executable} -m pip install --upgrade --pre -q "itk==5.3rc4.post3"

# Additionally we'll install numpy and torch to explore a variety of 
#    image data structures
!{sys.executable} -m pip install -q torch
!{sys.executable} -m pip install -q numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.6/83.6 MB 10.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.2/26.2 MB 47.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.2/17.2 MB 62.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 MB 13.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.9/75.9 MB 12.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.3/27.3 MB 43.4 MB/s eta 0:00:00


In [8]:
# Include ITK for DICOM reading
import itk

# Numpy for numpy.arrays
import numpy as np

# Torch for torch.tensors
import torch

In [9]:
# Install and import PyDICOM, then store file paths in list

!{sys.executable} -m pip install pydicom

import pydicom as di 
import os
from os import listdir
os.rename("tciaDownload", "tciaDownloadCOVID")
PathDicom = "tciaDownloadCOVID"
DCMFiles = [] 
for dirName, subdirList, fileList in os.walk(PathDicom):
    for filename in fileList:
        if ".dcm" in filename.lower():
            DCMFiles.append(os.path.join(dirName,filename))
print("Number of (.dcm) files =", len(DCMFiles))

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 26.1 MB/s eta 0:00:00
Number of (.dcm) files = 1045


In [10]:
ds=di.dcmread(DCMFiles[0])
print(ds)

Dataset.file_meta -------------------------------
(0002, 0000) File Meta Information Group Length  UL: 206
(0002, 0001) File Meta Information Version       OB: b'\x00\x01'
(0002, 0002) Media Storage SOP Class UID         UI: CT Image Storage
(0002, 0003) Media Storage SOP Instance UID      UI: 1.3.6.1.4.1.14519.5.2.1.99.1071.15771526784735199076362870087131
(0002, 0010) Transfer Syntax UID                 UI: Explicit VR Little Endian
(0002, 0012) Implementation Class UID            UI: 1.3.6.1.4.1.22213.1.143
(0002, 0013) Implementation Version Name         SH: '0.5'
(0002, 0016) Source Application Entity Title     AE: 'POSDA'
-------------------------------------------------
(0008, 0005) Specific Character Set              CS: 'ISO_IR 100'
(0008, 0008) Image Type                          CS: ['ORIGINAL', 'PRIMARY', 'AXIAL']
(0008, 0016) SOP Class UID                       UI: CT Image Storage
(0008, 0018) SOP Instance UID                    UI: 1.3.6.1.4.1.14519.5.2.1.99.1071.1577152

In [24]:
# Extract pixel data from image files

X_covid = []
y_covid = []
for k in DCMFiles:
    Images = di.read_file(k,force=True)
    if Image.pixel_array.shape == (512,512):
      X_covid.append(Image.pixel_array)
      y_covid.append(0) # 0 = covid data, 1 = cancer data    

In [25]:
X_covid

[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 

In [26]:
X_covid[0]


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint16)

In [27]:
X_covid[0].shape

(512, 512)

In [28]:
X_covid_array = np.array(X_covid)
print(X_covid_array.ndim)

3


In [29]:
X_covid_array.shape

(128, 512, 512)

In [30]:
X_covid_1darray = X_covid_array.reshape(-1)
X_covid_1darray.shape

(33554432,)

In [31]:
# Use the data frame to find the Series UID where the Modality is CT
dicom_data_dir = "tciaDownloadCOVID/"
ct_series_uid = df.at[df.Modality.eq('CT').idxmax(), 'Series UID']
dicom_ct_dir = os.path.join(dicom_data_dir, ct_series_uid)


# Load and sort the DICOM data into a volume - since no series_uid is
#    specified with this read command, it will load the first series in the directory.
dicom_image_large = itk.imread(dicom_ct_dir, itk.F)

# To save time for this demo, we subsample the image in the x and y dimensions
new_spacing = list(dicom_image_large.GetSpacing())
new_spacing[:2] = [x*3 for x in new_spacing[:2]]
new_size = list(dicom_image_large.GetLargestPossibleRegion().GetSize())
new_size[:2] = [x//3 for x in new_size[:2]]
dicom_image = itk.resample_image_filter(Input=dicom_image_large,
                                        output_spacing=new_spacing, 
                                        output_origin=dicom_image_large.GetOrigin(), 
                                        output_direction=dicom_image_large.GetDirection(),
                                        size=new_size)
print(f"New spacing = {new_spacing}")
print(f"New size = {new_size}")

RuntimeError: ignored

## Cancer Dataset

In [20]:
# Download a "Shared Cart" that has been previously 
#    created via the NBIA webset 
#    (https://nbia.cancerimagingarchive.net)
# cartName = "nbia-77761668716072016" # Their example shared cart
cartName = "nbia-47881669847357616" # Our lung cancer data's first subject
# cartName = "nbia-95651669947463238" # Cart with both cancer and covid data

# retrieve cart metadata
cart_data = tcia.getSharedCart(cartName)

# download the series_uids list and return dataframe of metadata
df = tcia.downloadSeries(cart_data)

# display dataframe
display(df)

Calling...  https://services.cancerimagingarchive.net/nbia-api/services/v1/getContentsByName?name=nbia-47881669847357616
Downloading... https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage?NewFileNames=Yes&SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.6655.2359.213534032021332276911485641315
Downloading... https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage?NewFileNames=Yes&SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.6655.2359.257508444832901632590301540805
Download Complete: 2 Series Instance UIDs (scans).


Series UID      Collection  \
0  1.3.6.1.4.1.14519.5.2.1.6655.2359.213534032021...  Lung-PET-CT-Dx   
1  1.3.6.1.4.1.14519.5.2.1.6655.2359.257508444832...  Lung-PET-CT-Dx   

                          Data Description URI     Subject ID  \
0  https://doi.org/10.7937/TCIA.2020.NNC2-0461  Lung_Dx-A0001   
1  https://doi.org/10.7937/TCIA.2020.NNC2-0461  Lung_Dx-A0001   

                                           Study UID Study Description  \
0  1.3.6.1.4.1.14519.5.2.1.6655.2359.165554066086...             Chest   
1  1.3.6.1.4.1.14519.5.2.1.6655.2359.165554066086...             Chest   

   Study Date Series Description Manufacturer Modality  \
0  04-04-2007                5mm      Philips       CT   
1  04-04-2007                5mm      Philips       CT   

               SOP Class UID Number of Images File Size Series Number  \
0  1.2.840.10008.5.1.4.1.1.2               64  33750912      3.000000   
1  1.2.840.10008.5.1.4.1.1.2               64  33750912      2.000000   

                                        License Name  \
0  Creative Commons Attribution 4.0 International...   
1  Creative Commons Attribution 4.0 International...   

                                    License URL Annotation Size  
0  https://creativecommons.org/licenses/by/4.0/               0  
1  https://creativecommons.org/licenses/by/4.0/               0

In [21]:
os.rename("tciaDownload", "tciaDownloadCancer")
PathDicom = "tciaDownloadCancer"
DCMFiles = [] 
for dirName, subdirList, fileList in os.walk(PathDicom):
    for filename in fileList:
        if ".dcm" in filename.lower():
            DCMFiles.append(os.path.join(dirName,filename))
print("Number of (.dcm) files =", len(DCMFiles))

Number of (.dcm) files = 128


In [32]:
# Extract pixel data from image files

X_cancer = []
y_cancer = []
for k in DCMFiles:
    Image = di.read_file(k,force=True)
    if Image.pixel_array.shape == (512,512):
      X_cancer.append(Image.pixel_array)
      y_cancer.append(1) # 0 = covid data, 1 = cancer data

In [33]:
X_cancer

[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 

In [35]:
type(X_cancer)

list

In [36]:
len(X_cancer)

128

In [37]:
type(X_cancer[0])

numpy.ndarray

In [38]:
X_cancer[0]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint16)

In [39]:
for n in X_cancer:
  print(n.shape)     

(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)
(512, 512)

In [41]:
X_cancer_array = np.array(X_cancer)
print(X_cancer_array.ndim)

3


In [42]:
X_cancer_array.shape

(128, 512, 512)

In [43]:
# Use the data frame to find the Series UID where the Modality is CT
dicom_data_dir = "tciaDownloadCancer/"
ct_series_uid = df.at[df.Modality.eq('CT').idxmax(), 'Series UID']
dicom_ct_dir = os.path.join(dicom_data_dir, ct_series_uid)

# Load and sort the DICOM data into a volume - since no series_uid is
#    specified with this read command, it will load the first series in the directory.
dicom_image_large = itk.imread(dicom_ct_dir, itk.F)

# To save time for this demo, we subsample the image in the x and y dimensions
new_spacing = list(dicom_image_large.GetSpacing())
new_spacing[:2] = [x*3 for x in new_spacing[:2]]
new_size = list(dicom_image_large.GetLargestPossibleRegion().GetSize())
new_size[:2] = [x//3 for x in new_size[:2]]
dicom_image = itk.resample_image_filter(Input=dicom_image_large,
                                        output_spacing=new_spacing, 
                                        output_origin=dicom_image_large.GetOrigin(), 
                                        output_direction=dicom_image_large.GetDirection(),
                                        size=new_size)
print(f"New spacing = {new_spacing}")
print(f"New size = {new_size}")

New spacing = [2.525390625, 2.525390625, 5.0]
New size = [170, 170, 64]


# Train Test Split 

In [44]:
# Convert to array 
X_covid = np.array(X_covid) 
X_cancer = np.array(X_cancer)

print(X_covid.ndim)
print(X_cancer.ndim)

# Split into training and testing sets for both types of images
X_covid_train, X_covid_test, y_covid_train, y_covid_test = train_test_split(
    X_covid, y_covid, test_size=0.2)
X_cancer_train, X_cancer_test, y_cancer_train, y_cancer_test = train_test_split(
    X_cancer, y_cancer, test_size=0.2)



3
3


In [45]:
X_covid.shape


(128, 512, 512)

In [46]:
X_cancer.shape


(128, 512, 512)

In [47]:
# Merge sets for both types of images
X_train = np.concatenate((X_covid_train, X_cancer_train), axis=0)
X_test = np.concatenate((X_covid_test, X_cancer_test), axis=0)
y_train = np.concatenate((y_covid_train, y_cancer_train), axis=0)
y_test = np.concatenate((y_covid_test, y_cancer_test), axis=0)


In [49]:
# Make labels into categories - either 0 or 1, for our model
y_train = LabelBinarizer().fit_transform(y_train)
y_train = to_categorical(y_train)

y_test = LabelBinarizer().fit_transform(y_test)
y_test = to_categorical(y_test)

In [52]:
ResNet50(
    include_top=True,
    weights=None,
    input_tensor=None,
    input_shape=(512, 512, 3),
    pooling=None,
    classes=1000
)

# Building and Visualizing Model

In [62]:
# Building Model
resnet = ResNet50(weights="imagenet", include_top=False,
    input_tensor=Input(shape=(224, 224, 3)))

model.compile(
        loss='categorical_crossentropy', 
        optimizer='adam', 
        metrics=['accuracy']
)


# model = ResNet50(include_top=True, weights='imagenet') 


94765736/94765736 [==============================] - 1s 0us/step


In [65]:
# training config:
epochs = 500
batch_size = 32


In [60]:
 # Preprocess image for model prediction
# This step handles scaling and normalization
# x = preprocess_input(X_train)

In [61]:
# # Make predictions
# predictions = model.predict(X_train)
# print('Predicted:', decode_predictions(predictions, top=3))

ValueError: ignored

In [66]:
model.summary()

Model: "resnet50"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_2 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv1_pad (ZeroPadding2D)      (None, 230, 230, 3)  0           ['input_2[0][0]']                
                                                                                                  
 conv1_conv (Conv2D)            (None, 112, 112, 64  9472        ['conv1_pad[0][0]']              
                                )                                                                 
                                                                                           

### Making Predictions

In [67]:
y_pred = model.predict(X_test, batch_size=batch_size)

ValueError: ignored