
Setup


In [1]:
import os
import sys
import matplotlib.pyplot as plt


# Upgrade pip, just in case...
!{sys.executable} -m pip install --upgrade -q pip

     |████████████████████████████████| 2.1 MB 5.4 MB/s 


## COVID Dataset

TCIA Basics

In [2]:
# Install requests for downloading data.
!{sys.executable} -m pip install --upgrade -q requests
!{sys.executable} -m pip install --upgrade -q pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 27.8 MB/s eta 0:00:00


In [3]:
import requests

tcia_utils_text = requests.get("https://github.com/kirbyju/TCIA_Notebooks/raw/main/tcia_utils.py")
with open('tcia_utils.py', 'wb') as f:
    f.write(tcia_utils_text.content)

In [4]:
import tcia_utils as tcia

In [5]:
# Download a "Shared Cart" that has been previously 
#    created via the NBIA webset 
#    (https://nbia.cancerimagingarchive.net)
# cartName = "nbia-77761668716072016" # Their example shared cart
# cartName = "nbia-47881669847357616" # Our lung cancer data's first subject
# cartName = "nbia-95651669947463238" # Cart with both cancer and covid data
cartName = "nbia-6761669942417940" # Cart with covid data

# retrieve cart metadata
cart_data = tcia.getSharedCart(cartName)

# download the series_uids list and return dataframe of metadata
df = tcia.downloadSeries(cart_data)

# display dataframe
display(df)

Calling...  https://services.cancerimagingarchive.net/nbia-api/services/v1/getContentsByName?name=nbia-6761669942417940
Downloading... https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage?NewFileNames=Yes&SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.99.1071.14850676509103506699400577275960
Downloading... https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage?NewFileNames=Yes&SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.99.1071.21083349907841416087078944245719
Downloading... https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage?NewFileNames=Yes&SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.99.1071.22090542070462647745743105373525
Downloading... https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage?NewFileNames=Yes&SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.99.1071.22366983673254100505145504004129
Downloading... https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage?NewFileNames=Yes&SeriesInstanceUID=1.3.6.1.4.

Series UID       Collection  \
0  1.3.6.1.4.1.14519.5.2.1.99.1071.14850676509103...  COVID-19-NY-SBU   
1  1.3.6.1.4.1.14519.5.2.1.99.1071.21083349907841...  COVID-19-NY-SBU   
2  1.3.6.1.4.1.14519.5.2.1.99.1071.22090542070462...  COVID-19-NY-SBU   
3  1.3.6.1.4.1.14519.5.2.1.99.1071.22366983673254...  COVID-19-NY-SBU   
4  1.3.6.1.4.1.14519.5.2.1.99.1071.30475546417294...  COVID-19-NY-SBU   
5  1.3.6.1.4.1.14519.5.2.1.99.1071.85179820664090...  COVID-19-NY-SBU   

  3rd Party Analysis                    Data Description URI Subject ID  \
0                 NO  https://doi.org/10.7937/TCIA.BBAG-2923    A034518   
1                 NO  https://doi.org/10.7937/TCIA.BBAG-2923    A034518   
2                 NO  https://doi.org/10.7937/TCIA.BBAG-2923    A034518   
3                 NO  https://doi.org/10.7937/TCIA.BBAG-2923    A034518   
4                 NO  https://doi.org/10.7937/TCIA.BBAG-2923    A034518   
5                 NO  https://doi.org/10.7937/TCIA.BBAG-2923    A034518   

                                           Study UID  \
0  1.3.6.1.4.1.14519.5.2.1.99.1071.28052166218470...   
1  1.3.6.1.4.1.14519.5.2.1.99.1071.28052166218470...   
2  1.3.6.1.4.1.14519.5.2.1.99.1071.28052166218470...   
3  1.3.6.1.4.1.14519.5.2.1.99.1071.28052166218470...   
4  1.3.6.1.4.1.14519.5.2.1.99.1071.28052166218470...   
5  1.3.6.1.4.1.14519.5.2.1.99.1071.28052166218470...   

                         Study Description  Study Date Series Description  \
0  CT ABD PELVISWITH CHEST IMAGES W IV CON  12-31-1900                2.0   
1  CT ABD PELVISWITH CHEST IMAGES W IV CON  12-31-1900      Body 3.000 CE   
2  CT ABD PELVISWITH CHEST IMAGES W IV CON  12-31-1900      Body 3.000 CE   
3  CT ABD PELVISWITH CHEST IMAGES W IV CON  12-31-1900        Lung 1.0 CE   
4  CT ABD PELVISWITH CHEST IMAGES W IV CON  12-31-1900        Body 5.0 CE   
5  CT ABD PELVISWITH CHEST IMAGES W IV CON  12-31-1900        Lung 5.0 CE   

  Manufacturer Modality              SOP Class UID Number of Images  \
0      TOSHIBA       CT  1.2.840.10008.5.1.4.1.1.2                2   
1      TOSHIBA       CT  1.2.840.10008.5.1.4.1.1.2              118   
2      TOSHIBA       CT  1.2.840.10008.5.1.4.1.1.2               89   
3      TOSHIBA       CT  1.2.840.10008.5.1.4.1.1.2              596   
4      TOSHIBA       CT  1.2.840.10008.5.1.4.1.1.2              120   
5      TOSHIBA       CT  1.2.840.10008.5.1.4.1.1.2              120   

   File Size Series Number                                       License Name  \
0    1314900      1.000000  Creative Commons Attribution 4.0 International...   
1  160721790      7.000000  Creative Commons Attribution 4.0 International...   
2  121222124      6.000000  Creative Commons Attribution 4.0 International...   
3  314916466      4.000000  Creative Commons Attribution 4.0 International...   
4   63405602      2.000000  Creative Commons Attribution 4.0 International...   
5   63405842      3.000000  Creative Commons Attribution 4.0 International...   

                                    License URL Annotation Size  
0  https://creativecommons.org/licenses/by/4.0/               0  
1  https://creativecommons.org/licenses/by/4.0/               0  
2  https://creativecommons.org/licenses/by/4.0/               0  
3  https://creativecommons.org/licenses/by/4.0/               0  
4  https://creativecommons.org/licenses/by/4.0/               0  
5  https://creativecommons.org/licenses/by/4.0/               0

In [6]:
# For this demo...

# Install itk for DICOM I/O and for reading DICOM into an itkImage 
#   that manages all DICOM field values, include acquistion details 
#   such as voxel image, image orientation, and image directions
#   which are critical to image processing and display
!{sys.executable} -m pip install --upgrade --pre -q "itk==5.3rc4.post3"

# Additionally we'll install numpy and torch to explore a variety of 
#    image data structures
!{sys.executable} -m pip install -q torch
!{sys.executable} -m pip install -q numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.9/75.9 MB 9.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 MB 11.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.2/26.2 MB 31.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.2/17.2 MB 19.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.3/27.3 MB 13.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.6/83.6 MB 11.3 MB/s eta 0:00:00


In [7]:
# Install and import PyDICOM, then store file paths in list

!{sys.executable} -m pip install pydicom

import pydicom as di 
import os
from os import listdir
os.rename("tciaDownload", "tciaDownloadCOVID")
PathDicom = "tciaDownloadCOVID"
DCMFiles = [] 
for dirName, subdirList, fileList in os.walk(PathDicom):
    for filename in fileList:
        if ".dcm" in filename.lower():
            DCMFiles.append(os.path.join(dirName,filename))
print("Number of (.dcm) files =", len(DCMFiles))

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 22.6 MB/s eta 0:00:00
Number of (.dcm) files = 1045


In [8]:
# Include ITK for DICOM reading
import itk

# Numpy for numpy.arrays
import numpy as np

# Torch for torch.tensors
import torch

# Install and import PyDICOM, then store file paths in list

!{sys.executable} -m pip install pydicom

import pydicom as di 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [9]:
# Extract pixel data from image files

X_covid = []
y_covid = []
for k in DCMFiles:
    Images = di.read_file(k,force=True)
    X_covid.append(Images.pixel_array)
    y_covid.append(0) # 0 = covid data, 1 = cancer data

In [18]:
X_covid

[array([[-2048, -2048, -2048, ..., -2048, -2048, -2048],
        [-2048, -2048, -2048, ..., -2048, -2048, -2048],
        [-2048, -2048, -2048, ..., -2048, -2048, -2048],
        ...,
        [-2048, -2048, -2048, ..., -2048, -2048, -2048],
        [-2048, -2048, -2048, ..., -2048, -2048, -2048],
        [-2048, -2048, -2048, ..., -2048, -2048, -2048]], dtype=int16),
 array([[-2048, -2048, -2048, ..., -2048, -2048, -2048],
        [-2048, -2048, -2048, ..., -2048, -2048, -2048],
        [-2048, -2048, -2048, ..., -2048, -2048, -2048],
        ...,
        [-2048, -2048, -2048, ..., -2048, -2048, -2048],
        [-2048, -2048, -2048, ..., -2048, -2048, -2048],
        [-2048, -2048, -2048, ..., -2048, -2048, -2048]], dtype=int16),
 array([[-2048, -2048, -2048, ..., -2048, -2048, -2048],
        [-2048, -2048, -2048, ..., -2048, -2048, -2048],
        [-2048, -2048, -2048, ..., -2048, -2048, -2048],
        ...,
        [-2048, -2048, -2048, ..., -2048, -2048, -2048],
        [-2048, -20

In [10]:
# Use the data frame to find the Series UID where the Modality is CT
dicom_data_dir = "tciaDownload/"
ct_series_uid = df.at[df.Modality.eq('CT').idxmax(), 'Series UID']
dicom_ct_dir = os.path.join(dicom_data_dir, ct_series_uid)


# Load and sort the DICOM data into a volume - since no series_uid is
#    specified with this read command, it will load the first series in the directory.
dicom_image_large = itk.imread(dicom_ct_dir, itk.F)

# To save time for this demo, we subsample the image in the x and y dimensions
new_spacing = list(dicom_image_large.GetSpacing())
new_spacing[:2] = [x*3 for x in new_spacing[:2]]
new_size = list(dicom_image_large.GetLargestPossibleRegion().GetSize())
new_size[:2] = [x//3 for x in new_size[:2]]
dicom_image = itk.resample_image_filter(Input=dicom_image_large,
                                        output_spacing=new_spacing, 
                                        output_origin=dicom_image_large.GetOrigin(), 
                                        output_direction=dicom_image_large.GetDirection(),
                                        size=new_size)
print(f"New spacing = {new_spacing}")
print(f"New size = {new_size}")

RuntimeError: ignored

## Cancer Dataset

In [11]:
# Download a "Shared Cart" that has been previously 
#    created via the NBIA webset 
#    (https://nbia.cancerimagingarchive.net)
# cartName = "nbia-77761668716072016" # Their example shared cart
cartName = "nbia-47881669847357616" # Our lung cancer data's first subject
# cartName = "nbia-95651669947463238" # Cart with both cancer and covid data

# retrieve cart metadata
cart_data = tcia.getSharedCart(cartName)

# download the series_uids list and return dataframe of metadata
df = tcia.downloadSeries(cart_data)

# display dataframe
display(df)

Calling...  https://services.cancerimagingarchive.net/nbia-api/services/v1/getContentsByName?name=nbia-47881669847357616
Downloading... https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage?NewFileNames=Yes&SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.6655.2359.213534032021332276911485641315
Downloading... https://services.cancerimagingarchive.net/nbia-api/services/v1/getImage?NewFileNames=Yes&SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.6655.2359.257508444832901632590301540805
Download Complete: 2 Series Instance UIDs (scans).


Series UID      Collection  \
0  1.3.6.1.4.1.14519.5.2.1.6655.2359.213534032021...  Lung-PET-CT-Dx   
1  1.3.6.1.4.1.14519.5.2.1.6655.2359.257508444832...  Lung-PET-CT-Dx   

                          Data Description URI     Subject ID  \
0  https://doi.org/10.7937/TCIA.2020.NNC2-0461  Lung_Dx-A0001   
1  https://doi.org/10.7937/TCIA.2020.NNC2-0461  Lung_Dx-A0001   

                                           Study UID Study Description  \
0  1.3.6.1.4.1.14519.5.2.1.6655.2359.165554066086...             Chest   
1  1.3.6.1.4.1.14519.5.2.1.6655.2359.165554066086...             Chest   

   Study Date Series Description Manufacturer Modality  \
0  04-04-2007                5mm      Philips       CT   
1  04-04-2007                5mm      Philips       CT   

               SOP Class UID Number of Images File Size Series Number  \
0  1.2.840.10008.5.1.4.1.1.2               64  33750912      3.000000   
1  1.2.840.10008.5.1.4.1.1.2               64  33750912      2.000000   

                                        License Name  \
0  Creative Commons Attribution 4.0 International...   
1  Creative Commons Attribution 4.0 International...   

                                    License URL Annotation Size  
0  https://creativecommons.org/licenses/by/4.0/               0  
1  https://creativecommons.org/licenses/by/4.0/               0

In [12]:
# For this demo...

# Install itk for DICOM I/O and for reading DICOM into an itkImage 
#   that manages all DICOM field values, include acquistion details 
#   such as voxel image, image orientation, and image directions
#   which are critical to image processing and display
!{sys.executable} -m pip install --upgrade --pre -q "itk==5.3rc4.post3"

# Additionally we'll install numpy and torch to explore a variety of 
#    image data structures
!{sys.executable} -m pip install -q torch
!{sys.executable} -m pip install -q numpy

In [13]:
# Include ITK for DICOM reading
import itk

# Numpy for numpy.arrays
import numpy as np

# Torch for torch.tensors
import torch

In [14]:
# Use the data frame to find the Series UID where the Modality is CT
dicom_data_dir = "tciaDownload/"
ct_series_uid = df.at[df.Modality.eq('CT').idxmax(), 'Series UID']
dicom_ct_dir = os.path.join(dicom_data_dir, ct_series_uid)

# Load and sort the DICOM data into a volume - since no series_uid is
#    specified with this read command, it will load the first series in the directory.
dicom_image_large = itk.imread(dicom_ct_dir, itk.F)

# To save time for this demo, we subsample the image in the x and y dimensions
new_spacing = list(dicom_image_large.GetSpacing())
new_spacing[:2] = [x*3 for x in new_spacing[:2]]
new_size = list(dicom_image_large.GetLargestPossibleRegion().GetSize())
new_size[:2] = [x//3 for x in new_size[:2]]
dicom_image = itk.resample_image_filter(Input=dicom_image_large,
                                        output_spacing=new_spacing, 
                                        output_origin=dicom_image_large.GetOrigin(), 
                                        output_direction=dicom_image_large.GetDirection(),
                                        size=new_size)
print(f"New spacing = {new_spacing}")
print(f"New size = {new_size}")

New spacing = [2.525390625, 2.525390625, 5.0]
New size = [170, 170, 64]


In [15]:
# Install and import PyDICOM, then store file paths in list

!{sys.executable} -m pip install pydicom

import pydicom as di 
import os
from os import listdir
os.rename("tciaDownload", "tciaDownloadCancer")
PathDicom = "tciaDownloadCancer"
DCMFiles = [] 
for dirName, subdirList, fileList in os.walk(PathDicom):
    for filename in fileList:
        if ".dcm" in filename.lower():
            DCMFiles.append(os.path.join(dirName,filename))
print("Number of (.dcm) files =", len(DCMFiles))

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Number of (.dcm) files = 128


In [16]:
# Extract pixel data from image files

X_cancer = []
y_cancer = []
for k in DCMFiles:
    Images = di.read_file(k,force=True)
    X_cancer.append(Images.pixel_array)
    y_cancer.append(0) # 0 = covid data, 1 = cancer data

In [17]:
X_cancer

[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 

# Train Test Split 

In [21]:
#Import Dependencies

from builtins import range, input

from tensorflow.keras.layers import Input, Lambda, Dense, Flatten, AveragePooling2D, Dropout
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.metrics import confusion_matrix, roc_curve
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

import cv2
from glob import glob

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
from tensorflow.keras.utils import to_categorical

In [22]:
# Convert to array 
X_covid = np.array(X_covid) 
X_cancer = np.array(X_cancer)

# Split into training and testing sets for both types of images
X_covid_train, X_covid_test, y_covid_train, y_covid_test = train_test_split(
    X_covid, y_covid, test_size=0.2)
X_cancer_train, X_cancer_test, y_cancer_train, y_cancer_test = train_test_split(
    X_cancer, y_cancer, test_size=0.2)

